# -*- coding: utf-8 -*-
"""Курсач по ии.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lcSRY1Ls7iHgPdQe0DooS9wL8ZbIhqNx
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

url = "https://raw.githubusercontent.com/VaryaKurtseva/AI/main/Heart_Disease_Prediction.csv"
df = pd.read_csv(url)
df

df.info()

def categorial(df):
  meaning = df['Heart Disease'].astype(str)
  for i in range(len(meaning)):
    if meaning[i] == "Presence":
      meaning[i] = 1
    else:
      meaning[i] = 0
  return meaning
newHeartDisaes = categorial(df)
newHeartDisaes
newDf = pd.DataFrame({
    "Возраст":df['Age'] ,
    "Пол": df['Sex'],
    "Тип боли в груди": df['Chest pain type'],
    "BP": df['BP'],
    "Холестерин": df['Cholesterol'],
    "FBS больше 120": df['FBS over 120'],
    "Результаты ЭКГ": df['EKG results'],
    "Макс ЧСС": df['Max HR'],
    "Упражнения при стенокардии": df['Exercise angina'],
    "Депрессия ST": df['ST depression'],
    "Наклон ST": df['Slope of ST'],
    "Количество сосудов флюоро": df['Number of vessels fluro'],
    "Таллий": df['Thallium'],
    "Сердечное заболевание": newHeartDisaes

})

newDf.head()

# Подготовка X (признаки) и y (целевая переменная)
X = newDf[['Возраст','BP','Холестерин','Макс ЧСС']]
y = newDf['Сердечное заболевание']
# Иницилизируем веса
w0 = 0.01
w1 = 0.01
w2 = 0.01
w3 = 0.01
w4 = 0.01
predicts = []
for i in range(len(y)):
  y_predict = w0 + w1*X.iloc[i]['Возраст'] + w2*X.iloc[i]['BP'] + w3*X.iloc[i]['Холестерин'] + w4*X.iloc[i]['Холестерин']
  predicts.append(y_predict)

cost_function =[]
def getCostFunctions():
  for i in range(len(y)):
    cost_function.append((y.iloc[i] - predicts[i])**2)
getCostFunctions()